### ISSUE TITLE
GetMap fails with panic, regardless of err given in return assignment

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast-go-client#105]
Hi Team, I have below scenario and question

1] Client tries to connect with invalid credentials
2] Client returns proper error
3] However, in my sample code, I call `GetMap` as below afterwards, cluster size is `0`
```$go
flow.createdMap, err = flow.client.GetMap(name); if err != nil {
			log.Printf("Error is %v", err)
			return flow
		}
```

It panics as below, does not it need to assign `err`?
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13fdd66]

goroutine 6 [running]:
testing.tRunner.func1(0xc42035c0f0)
        /usr/local/Cellar/go/1.9.2/libexec/src/testing/testing.go:711 +0x2d2
panic(0x14cd7e0, 0x1834d00)
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
github.com/hazelcast/go-client/internal/protocol.StringCalculateSize(...)
        /Users/baris/Go/src/github.com/hazelcast/go-client/internal/protocol/consts.go:28
github.com/hazelcast/go-client/internal/protocol.AddressCalculateSize(...)
        /Users/baris/Go/src/github.com/hazelcast/go-client/internal/protocol/consts.go:32
github.com/hazelcast/go-client/internal/protocol.ClientCreateProxyCalculateSize(...)
        /Users/baris/Go/src/github.com/hazelcast/go-client/internal/protocol/client_createproxy.go:25
github.com/hazelcast/go-client/internal/protocol.ClientCreateProxyEncodeRequest(0xc4201845f0, 0xc420184490, 0x0, 0xc420115080)
        /Users/baris/Go/src/github.com/hazelcast/go-client/internal/protocol/client_createproxy.go:31 +0x26
github.com/hazelcast/go-client/internal.(*ProxyManager).createProxy(0xc4201a1e00, 0xc420184490, 0xc4201845f0, 0x15, 0x1870700, 0xc420013800, 0x15)
        /Users/baris/Go/src/github.com/hazelcast/go-client/internal/proxy_manager.go:63 +0x51
github.com/hazelcast/go-client/internal.(*ProxyManager).GetOrCreateProxy(0xc4201a1e00, 0x157465a, 0x12, 0xc420164b96, 0x3, 0x0, 0x0, 0x0, 0x0)
        /Users/baris/Go/src/github.com/hazelcast/go-client/internal/proxy_manager.go:52 +0x254
github.com/hazelcast/go-client/internal.(*HazelcastClient).GetDistributedObject(0xc4202567e0, 0x157465a, 0x12, 0xc420164b96, 0x3, 0x143bb16, 0xc42021abc0, 0x2a, 0xc420164b96)
        /Users/baris/Go/src/github.com/hazelcast/go-client/internal/client.go:51 +0x5b
github.com/hazelcast/go-client/internal.(*HazelcastClient).GetMap(0xc4202567e0, 0xc420164b96, 0x3, 0xc420164b96, 0x3, 0x0, 0x0)
        /Users/baris/Go/src/github.com/hazelcast/go-client/internal/client.go:46 +0x58

```

**Comment by lazerion** [comment]
Hi Team, is there a decision or implementation PR regarding this comment? I observe it, after latest changes.

**Comment by SaitTalhaNisanci** [comment]
In our standup meeting we have decided not to handle this case, so closing the issue.
