### ISSUE TITLE
client.Shutdown() leaves 5 go routines

### ISSUE THREAD

**Issue by roidelapluie** [hazelcast/hazelcast-go-client#242]
After doing a client.Shutdown() there are 5 go routines left. This is a huge leak.

```
goroutine 21 [running]:
runtime/pprof.writeGoroutineStacks(0x9f3e40, 0xc4200c41c0, 0x411ef9, 0xc4201a9800)
	/home/roidelapluie/godist/go/src/runtime/pprof/pprof.go:650 +0xa7
runtime/pprof.writeGoroutine(0x9f3e40, 0xc4200c41c0, 0x2, 0xc420021000, 0x9f3c40)
	/home/roidelapluie/godist/go/src/runtime/pprof/pprof.go:639 +0x44
runtime/pprof.(*Profile).WriteTo(0xd11240, 0x9f3e40, 0xc4200c41c0, 0x2, 0xc4200c41c0, 0x9f45a0)
	/home/roidelapluie/godist/go/src/runtime/pprof/pprof.go:310 +0x3e4
net/http/pprof.handler.ServeHTTP(0xc4201e2971, 0x9, 0x9f8b80, 0xc4200c41c0, 0xc420184300)
	/home/roidelapluie/godist/go/src/net/http/pprof/pprof.go:237 +0x1b8
net/http/pprof.Index(0x9f8b80, 0xc4200c41c0, 0xc420184300)
	/home/roidelapluie/godist/go/src/net/http/pprof/pprof.go:248 +0x1d1
net/http.HandlerFunc.ServeHTTP(0x9ac180, 0x9f8b80, 0xc4200c41c0, 0xc420184300)
	/home/roidelapluie/godist/go/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0xd1f860, 0x9f8b80, 0xc4200c41c0, 0xc420184300)
	/home/roidelapluie/godist/go/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc4201b6820, 0x9f8b80, 0xc4200c41c0, 0xc420184300)
	/home/roidelapluie/godist/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4201d8e60, 0x9f9900, 0xc4201b2680)
	/home/roidelapluie/godist/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/home/roidelapluie/godist/go/src/net/http/server.go:2795 +0x27b

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7faf0aff4f00, 0x72, 0x0)
	/home/roidelapluie/godist/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4201c4218, 0x72, 0xc420038000, 0x0, 0x0)
	/home/roidelapluie/godist/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4201c4218, 0xffffffffffffff00, 0x0, 0x0)
	/home/roidelapluie/godist/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc4201c4200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/roidelapluie/godist/go/src/internal/poll/fd_unix.go:372 +0x1a8
net.(*netFD).accept(0xc4201c4200, 0xc4201d8ee0, 0xc42007dd88, 0x402a68)
	/home/roidelapluie/godist/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc4201ac150, 0xc42007ddb8, 0x4019c7, 0xc4201d8ee0)
	/home/roidelapluie/godist/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc4201ac150, 0xc42007de00, 0xc42007de08, 0x18)
	/home/roidelapluie/godist/go/src/net/tcpsock.go:246 +0x49
net/http.tcpKeepAliveListener.Accept(0xc4201ac150, 0x9abf70, 0xc4201d8e60, 0x9f99c0, 0xc4201a9110)
	/home/roidelapluie/godist/go/src/net/http/server.go:3216 +0x2f
net/http.(*Server).Serve(0xc4201b6820, 0x9f9040, 0xc4201ac150, 0x0, 0x0)
	/home/roidelapluie/godist/go/src/net/http/server.go:2770 +0x1a5
net/http.(*Server).ListenAndServe(0xc4201b6820, 0xc4201b6820, 0xc4201a8ff0)
	/home/roidelapluie/godist/go/src/net/http/server.go:2711 +0xa9
net/http.ListenAndServe(0x7ffdc80d66a0, 0xe, 0x0, 0x0, 0x858f7a, 0x0)
	/home/roidelapluie/godist/go/src/net/http/server.go:2969 +0x7a
main.main()
	/home/roidelapluie/go/src/atobepx305.atos-srv.net/isocial/monitoring/hazelcast_exporter/main.go:35 +0x10b

goroutine 110 [chan receive]:
atobepx305.atos-srv.net/isocial/monitoring/hazelcast_exporter/vendor/github.com/hazelcast/hazelcast-go-client/internal.(*clusterService).process(0xc42021b1f0)
	/home/roidelapluie/go/src/atobepx305.atos-srv.net/isocial/monitoring/hazelcast_exporter/vendor/github.com/hazelcast/hazelcast-go-client/internal/cluster.go:108 +0x49
created by atobepx305.atos-srv.net/isocial/monitoring/hazelcast_exporter/vendor/github.com/hazelcast/hazelcast-go-client/internal.newClusterService
	/home/roidelapluie/go/src/atobepx305.atos-srv.net/isocial/monitoring/hazelcast_exporter/vendor/github.com/hazelcast/hazelcast-go-client/internal/cluster.go:62 +0x26a

goroutine 111 [select]:
atobepx305.atos-srv.net/isocial/monitoring/hazelcast_exporter/vendor/github.com/hazelcast/hazelcast-go-client/internal.(*listenerService).process(0xc4201c4480)
	/home/roidelapluie/go/src/atobepx305.atos-srv.net/isocial/monitoring/hazelcast_exporter/vendor/github.com/hazelcast/hazelcast-go-client/internal/listener.go:117 +0x2f9
created by atobepx305.atos-srv.net/isocial/monitoring/hazelcast_exporter/vendor/github.com/hazelcast/hazelcast-go-client/internal.newListenerService
	/home/roidelapluie/go/src/atobepx305.atos-srv.net/isocial/monitoring/hazelcast_exporter/vendor/github.com/hazelcast/hazelcast-go-client/internal/listener.go:90 +0x328

goroutine 112 [chan receive]:
atobepx305.atos-srv.net/isocial/monitoring/hazelcast_exporter/vendor/github.com/hazelcast/hazelcast-go-client/internal.(*listenerService).connectToAllMembersPeriodically(0xc4201c4480)
	/home/roidelapluie/go/src/atobepx305.atos-srv.net/isocial/monitoring/hazelcast_exporter/vendor/github.com/hazelcast/hazelcast-go-client/internal/listener.go:109 +0x48
created by atobepx305.atos-srv.net/isocial/monitoring/hazelcast_exporter/vendor/github.com/hazelcast/hazelcast-go-client/internal.newListenerService
	/home/roidelapluie/go/src/atobepx305.atos-srv.net/isocial/monitoring/hazelcast_exporter/vendor/github.com/hazelcast/hazelcast-go-client/internal/listener.go:93 +0x397

goroutine 114 [select]:
atobepx305.atos-srv.net/isocial/monitoring/hazelcast_exporter/vendor/github.com/hazelcast/hazelcast-go-client/internal.(*Connection).writePool(0xc42054a1c0)
	/home/roidelapluie/go/src/atobepx305.atos-srv.net/isocial/monitoring/hazelcast_exporter/vendor/github.com/hazelcast/hazelcast-go-client/internal/connection.go:88 +0x14b
created by atobepx305.atos-srv.net/isocial/monitoring/hazelcast_exporter/vendor/github.com/hazelcast/hazelcast-go-client/internal.newConnection
	/home/roidelapluie/go/src/atobepx305.atos-srv.net/isocial/monitoring/hazelcast_exporter/vendor/github.com/hazelcast/hazelcast-go-client/internal/connection.go:76 +0x5c7

goroutine 115 [IO wait]:
internal/poll.runtime_pollWait(0x7faf0aff4c90, 0x72, 0xc420059e18)
	/home/roidelapluie/godist/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4201c4598, 0x72, 0xffffffffffffff00, 0x9f4a80, 0xce1670)
	/home/roidelapluie/godist/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4201c4598, 0xc4206e2000, 0x4000, 0x4000)
	/home/roidelapluie/godist/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4201c4580, 0xc4206e2000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
	/home/roidelapluie/godist/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc4201c4580, 0xc4206e2000, 0x4000, 0x4000, 0x1a, 0xc4201a0260, 0xc42054a270)
	/home/roidelapluie/godist/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4201ac720, 0xc4206e2000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
	/home/roidelapluie/godist/go/src/net/net.go:176 +0x6a
atobepx305.atos-srv.net/isocial/monitoring/hazelcast_exporter/vendor/github.com/hazelcast/hazelcast-go-client/internal.(*Connection).read(0xc42054a1c0)
	/home/roidelapluie/go/src/atobepx305.atos-srv.net/isocial/monitoring/hazelcast_exporter/vendor/github.com/hazelcast/hazelcast-go-client/internal/connection.go:133 +0xa9
created by atobepx305.atos-srv.net/isocial/monitoring/hazelcast_exporter/vendor/github.com/hazelcast/hazelcast-go-client/internal.newConnection
	/home/roidelapluie/go/src/atobepx305.atos-srv.net/isocial/monitoring/hazelcast_exporter/vendor/github.com/hazelcast/hazelcast-go-client/internal/connection.go:77 +0x5ec

goroutine 122 [runnable]:
syscall.Syscall(0x0, 0x5, 0xc4201a9211, 0x1, 0xffffffffffffffff, 0x0, 0xb)
	/home/roidelapluie/godist/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x5, 0xc4201a9211, 0x1, 0x1, 0xc4201b2100, 0x0, 0x0)
	/home/roidelapluie/godist/go/src/syscall/zsyscall_linux_amd64.go:749 +0x5f
syscall.Read(0x5, 0xc4201a9211, 0x1, 0x1, 0xc42053aec0, 0x404fa5, 0xc4201be8a0)
	/home/roidelapluie/godist/go/src/syscall/syscall_unix.go:162 +0x49
internal/poll.(*FD).Read(0xc4201c4280, 0xc4201a9211, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/roidelapluie/godist/go/src/internal/poll/fd_unix.go:153 +0x118
net.(*netFD).Read(0xc4201c4280, 0xc4201a9211, 0x1, 0x1, 0xc420551da0, 0x0, 0x312e31322e323731)
	/home/roidelapluie/godist/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4201ac160, 0xc4201a9211, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/roidelapluie/godist/go/src/net/net.go:176 +0x6a
net/http.(*connReader).backgroundRead(0xc4201a9200)
	/home/roidelapluie/godist/go/src/net/http/server.go:668 +0x5a
created by net/http.(*connReader).startBackgroundRead
	/home/roidelapluie/godist/go/src/net/http/server.go:664 +0xce

```

**Comment by sancar** [comment]
At shutdown, we signal the go-routines to close. But we do not wait for them to be get closed. They will be closed eventually. That being said, We don't have a test specially check if they are closing eventually. It is clear that we should add one. 

Do you think this explained behaviour is correct ? Should we make sure for all processes to get closed before shutdown returns to the caller ?

**Comment by roidelapluie** [comment]
I do not see them close at all. I will publish a piece of code soon to explain my usecase.

**Comment by roidelapluie** [comment]
Here is the code https://github.com/Inuits/hazelcast_exporter

Every 30 seconds we open a new hazelcast connection then close it. Because the go routines stay forever, the program stops functioning after a few minutes.

**Comment by roidelapluie** [comment]
Thank you! I will give this a shot!

**Comment by roidelapluie** [comment]
The bug is indeed fixed!

**Comment by SaitTalhaNisanci** [comment]
Good to hear @roidelapluie.

**Comment by zbikmarc** [comment]
@SaitTalhaNisanci 
I think this problems still exists.
I did small adjustment in `samples/helloworld/one.go` to run it five times and sleep 10 sec between.

```go
func main() {
    for i := 0; i< 5; i++ {
        clientConfig := hazelcast.NewConfig()
        fmt.Println("Cluster name: ", clientConfig.GroupConfig().Name())

        clientConfig.NetworkConfig().AddAddress("127.0.0.1:5701")
        fmt.Println("Cluster discovery: ", clientConfig.NetworkConfig().Addresses())

        client, _ := hazelcast.NewClientWithConfig(clientConfig)

        client.Shutdown()

        time.Sleep(10 * time.Second)
    }
}
```

It is supposed to close connection after every loop, isn't it?

But when I do `lsof -p <PID>` it shows me additional connection in `ESTABLISHED` stated after every loop and none of them are closed. Despite that I clearly can see:
```
INFO: hz.client_5 [dev] [0.5-SNAPSHOT] HazelcastClient 0.5-SNAPSHOT is SHUTTING_DOWN
(...)
INFO: hz.client_5 [dev] [0.5-SNAPSHOT] HazelcastClient 0.5-SNAPSHOT is SHUTDOWN
```

**Comment by SaitTalhaNisanci** [comment]
@zbikmarc I think this doesnt cause any leakage problem. Otherwise this test would fail `https://github.com/hazelcast/hazelcast-go-client/blob/master/test/client_test.go#L61`.

I think this is because the socket wasnt closed explicitly in shutdown. 
`https://github.com/hazelcast/hazelcast-go-client/pull/429` this should fix it, I have checked it manually and it seems resolved, let me know after the merge.

**Comment by zbikmarc** [comment]
@SaitTalhaNisanci 
Thanks! Looks like this solves problem of `one`. Now I need to force `hazelcast_exporter` to compile with it but this is totally different story of `use of internal package not allowed` :)

Thanks again!
