### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference                                                                   

### ISSUE THREAD

**Issue by roidelapluie** [hazelcast/hazelcast-go-client#274]
Java Spring Boot has the ability to cache objects in hazelcast.

Those objects can not be read with go/hazelcast:

```
panic: runtime error: invalid memory address or nil pointer dereference                                                                   
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x50cccb]

goroutine 1 [running]:
local/isocial/boof/vendor/github.com/hazelcast/hazelcast-go-client/internal/serialization.(*Service).ToObject(0xc4201982a
0, 0xc4201a8940, 0x89b0a0, 0xc42023ec50, 0x0, 0x0)
        /home/roidelapluie/go/src/local/isocial/boof/vendor/github.com/hazelcast/hazelcast-go-client/internal/serializati
on/serialization.go:74 +0x14b
local/isocial/boof/vendor/github.com/hazelcast/hazelcast-go-client/internal/colutil.DataToObjectPairCollection(0xc4201b60
08, 0x1, 0x1, 0xc4201982a0, 0x5d4b94, 0xc420248a80, 0xc420240930, 0x0, 0x0)
        /home/roidelapluie/go/src/local/isocial/boof/vendor/github.com/hazelcast/hazelcast-go-client/internal/colutil/uti
l.go:64 +0x124
local/isocial/boof/vendor/github.com/hazelcast/hazelcast-go-client/internal.(*proxy).decodeToPairSliceAndError(0xc4202021
20, 0xc420240930, 0x0, 0x0, 0x9871e0, 0x412318, 0x10, 0x8ba740, 0x1, 0xc42023ec00)
        /home/roidelapluie/go/src/local/isocial/boof/vendor/github.com/hazelcast/hazelcast-go-client/internal/proxy.go:22
5 +0x94
local/isocial/boof/vendor/github.com/hazelcast/hazelcast-go-client/internal.(*mapProxy).EntrySet(0xc4201cc018, 0xc4201769
60, 0xc420022f00, 0x11, 0xcecbc0, 0x0)
        /home/roidelapluie/go/src/local/isocial/boof/vendor/github.com/hazelcast/hazelcast-go-client/internal/map.go:408
+0x95
main.fillMaps(0xc420026ed0, 0xe, 0xc420026ef0, 0xe, 0xc420022e80, 0x20, 0xc42016c4c0, 0x1, 0x1, 0x9d7340, ...)
        /home/roidelapluie/go/src/local/isocial/boof/boof.go:57 +0x736
main.run(0xc420026ed0, 0xe, 0xc420026ef0, 0xe, 0xc420022e80, 0x20, 0xc42016c4c0, 0x1, 0x1)
        /home/roidelapluie/go/src/local/isocial/boof/boof.go:27 +0x1cb
main.main()
        /home/roidelapluie/go/src/local/isocial/boof/main.go:33
```

rev 204d50f544905524548dfac0718134e836d5fbcf

**Comment by furkansenharputlu** [comment]
Are the objects serialized by using `Java Serializable` ? If so, they cannot be deserialized in Go Client. To handle this, you need to use Hazelcast Native Serialization. You should define your objects in `IdentifiedDataSerializable` or `Portable` types. 

See the following examples:

https://github.com/hazelcast/hazelcast-go-client/blob/master/sample/serialization/identified/identified_data_serializable_example.go

https://github.com/hazelcast/hazelcast-go-client/blob/master/sample/serialization/portable/portable_example.go

**Comment by roidelapluie** [comment]
Anyway I think we could handle this with a proper error instead of a panic?

**Comment by furkansenharputlu** [comment]
Yeah, it could be better to return a proper error. I will handle it. Also, if you don't need the object in Go Client, you can save it as [HeapData](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/HeapData.java) on Java side. Then, Go serialization does not try to deserialize the data. It returns as it is.
