### ISSUE TITLE
hazelcast-go-client should work with hazelcast-cloud & ssl enabled

### ISSUE THREAD

**Issue by kloia-hz-daas** [hazelcast/hazelcast-go-client#401]
Go version: 1.10
Hazelcast Go Client version: master-snapshot
Hazelcast server version: 3.10.5
Number of the clients: 1
Cluster size, i.e. the number of Hazelcast cluster members: 2
OS version : Windows/Linux/OSX: client osx

#### Expected behaviour
hazelcast-go-client should work with hazelcast-cloud & ssl enabled

#### Actual behaviour

server side gives following error:
```
22:35:37,408  INFO || -  [TcpIpConnectionManager] hz._hzInstance_1_test.IO.thread-Acceptor - [100.96.9.6]:32012 [test] [3.10.5] Established socket connection between /100.96.9.6:32012 and /85.148.79.29:56080
22:35:37,653  WARN || -  [TcpIpConnection] hz._hzInstance_1_test.IO.thread-in-1 - [100.96.9.6]:32012 [test] [3.10.5] Connection[id=65, /100.96.9.6:32012->/85.148.79.29:56080, endpoint=null, alive=false, type=NONE] closed. Reason: Exception in Connection[id=65, /100.96.9.6:32012->/85.148.79.29:56080, endpoint=null, alive=true, type=NONE], thread=hz._hzInstance_1_test.IO.thread-in-1
javax.net.ssl.SSLHandshakeException: null cert chain
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1529) ~[?:1.8.0_171]
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535) ~[?:1.8.0_171]
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813) ~[?:1.8.0_171]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[?:1.8.0_171]
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[?:1.8.0_171]
	at com.hazelcast.nio.ssl.SSLChannel.unwrap(SSLChannel.java:268) ~[hazelca
```

#### Steps to reproduce the behaviour

```
	cfg := hazelcast.NewConfig()
	sslConfig := cfg.NetworkConfig().SSLConfig()
	sslConfig.SetEnabled(true)
	sslConfig.SetCaPath("/Users/lion/Downloads/hzcloud_36_keys/client.truststore")
	sslConfig.AddClientCertAndEncryptedKeyPath("/Users/xxx/Downloads/hzcloud_36_keys/cert.pem", "/Users/xxx/Downloads/hzcloud_36_keys/key.pem", "xxxx")
	sslConfig.ServerName = "hazelcast.cloud"
	sslConfig.InsecureSkipVerify = true
	cfg.GroupConfig().SetName("test")
	cfg.GroupConfig().SetPassword("xxxx")
	discoveryCfg := config.NewCloudConfig()
	discoveryCfg.SetEnabled(true)
	discoveryCfg.SetDiscoveryToken("xxxxx")
	cfg.NetworkConfig().SetCloudConfig(discoveryCfg)
	client, _ := hazelcast.NewClientWithConfig(cfg)
	mp, _ := client.GetMap("map")
	mp.Put("key", "value")
	size, _ := mp.Size()
	value, _ := mp.Get("key")
	log.Println("Size:", size)
	log.Println("Value:", value)
	client.Shutdown()
```
client logs:
```
2018/12/03 23:35:27 New State :  STARTING
2018/12/03 23:35:32 The following error occurred while trying to connect to: 100.96.9.6:32012 in cluster. attempt  1  of  2  error:  EOF
2018/12/03 23:35:33 The following error occurred while trying to connect to: 100.96.16.2:32012 in cluster. attempt  1  of  2  error:  EOF
2018/12/03 23:35:33 The following error occurred while trying to connect to: 127.0.0.1:5701 in cluster. attempt  1  of  2  error:  address translator could not translate address:127.0.0.1:5701
2018/12/03 23:35:37 The following error occurred while trying to connect to: 100.96.9.6:32012 in cluster. attempt  2  of  2  error:  EOF
2018/12/03 23:35:37 The following error occurred while trying to connect to: 100.96.16.2:32012 in cluster. attempt  2  of  2  error:  EOF
2018/12/03 23:35:37 The following error occurred while trying to connect to: 127.0.0.1:5701 in cluster. attempt  2  of  2  error:  address translator could not translate address:127.0.0.1:5701
panic: interface conversion: core.Address is nil, not *proto.Address

goroutine 1 [running]:
github.com/hazelcast/hazelcast-go-client/internal.(*proxyManager).createProxy(0xc4200a9c20, 0x13735c1, 0x12, 0x136ffd2, 0x3, 0xc42020a500, 0x15, 0xc4200e2630, 0x13b5a20)
```

**Comment by SaitTalhaNisanci** [comment]
I think this problem occurs because of `sslConfig.AddClientCertAndEncryptedKeyPath("/Users/xxx/Downloads/hzcloud_36_keys/cert.pem", "/Users/xxx/Downloads/hzcloud_36_keys/key.pem", "xxxx")` here this returns an error: `x509: no DEK-Info header in block`.

As far as I know in Go while decrypting a pem file, `Dek-Info` is used. `https://github.com/golang/go/blob/master/src/crypto/x509/pem_decrypt.go#L116`

It is mentioned here:`https://github.com/hazelcast/hazelcast-go-client/blob/master/config/ssl_config.go#L83`

**Comment by SaitTalhaNisanci** [comment]
Closing this and the reason is explained in the comment, if we can find a way to use pem files without `Dek-info` we can reoopen this.
