### ISSUE TITLE
hazelcast 4.0+ support?

### ISSUE THREAD

**Issue by justinrush** [hazelcast/hazelcast-go-client#496]
Go version: 1.15
Hazelcast Go Client version: v0.6.0
Hazelcast server version: 4.1
Number of the clients: 1
Cluster size, i.e. the number of Hazelcast cluster members: 1
OS version : Windows / Linux

#### Expected behaviour
Connection should succeed

#### Actual behaviour
exception thrown in hazelcast logs:
```
2020-11-12 00:30:53,925 [ WARN] [hz.sleepy_kare.IO.thread-in-1] [c.h.i.s.t.TcpServerConnection]: [172.19.0.2]:5701 [dev] [4.1] Connection[id=2, /172.19.0.2:5701->/172.19.0.1:57598, qualifier=null, endpoint=null, alive=false, connectionType=NONE, planeIndex=-1] closed. Reason: Exception in Connection[id=2, /172.19.0.2:5701->/172.19.0.1:57598, qualifier=null, endpoint=null, alive=true, connectionType=NONE, planeIndex=-1], thread=hz.sleepy_kare.IO.thread-in-1
java.lang.IllegalStateException: Unknown protocol: CB2
        at com.hazelcast.internal.server.tcp.UnifiedProtocolDecoder.onRead(UnifiedProtocolDecoder.java:117) ~[hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:137) ~[hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.internal.networking.nio.NioPipeline.lambda$start$0(NioPipeline.java:127) ~[hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.internal.networking.nio.NioThread.processTaskQueue(NioThread.java:355) [hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:290) [hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.internal.networking.nio.NioThread.executeRun(NioThread.java:249) [hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [hazelcast-all-4.1.jar:4.1]
```

logs from the goclient:
```
2020/11/12 16:16:39 github.com/hazelcast/hazelcast-go-client/internal.(*lifecycleService).fireLifecycleEvent
INFO: hz.client_1 [dev] [0.5-SNAPSHOT] HazelcastClient 0.5-SNAPSHOT is STARTING
2020/11/12 16:16:39 github.com/hazelcast/hazelcast-go-client/internal.(*clusterService).connectToAddress
INFO: hz.client_1 [dev] [0.5-SNAPSHOT] Trying to connect to localhost:5701 as owner member.
2020/11/12 16:16:39 github.com/hazelcast/hazelcast-go-client/internal.(*Connection).close
WARN: hz.client_1 [dev] [0.5-SNAPSHOT] Connection : %!v(PANIC=String method: interface conversion: interface is nil, not core.Address)  closed, err:  EOF
2020/11/12 16:16:40 github.com/hazelcast/hazelcast-go-client/internal.(*clusterService).connectToAddress
WARN: hz.client_1 [dev] [0.5-SNAPSHOT] Error during initial connection to localhost:5701 error: packet is not sent
2020/11/12 16:16:43 github.com/hazelcast/hazelcast-go-client/internal.(*clusterService).connectToAddress
INFO: hz.client_1 [dev] [0.5-SNAPSHOT] Trying to connect to localhost:5701 as owner member.
2020/11/12 16:16:43 github.com/hazelcast/hazelcast-go-client/internal.(*Connection).close
WARN: hz.client_1 [dev] [0.5-SNAPSHOT] Connection : %!v(PANIC=String method: interface conversion: interface is nil, not core.Address)  closed, err:  EOF
2020/11/12 16:16:44 github.com/hazelcast/hazelcast-go-client/internal.(*clusterService).connectToAddress
WARN: hz.client_1 [dev] [0.5-SNAPSHOT] Error during initial connection to localhost:5701 error: packet is not sent
```

#### Steps to reproduce the behaviour

1. docker run -p 5701:5701 hazelcast/hazelcast:4.1
2. this go code:
```golang
package main

import (
	"fmt"
	"log"

	"github.com/hazelcast/hazelcast-go-client"
)

func main() {

	config := hazelcast.NewConfig()
	config.NetworkConfig().AddAddress("localhost:5701")
	config.NetworkConfig().SetSmartRouting(false)
	hz, _ := hazelcast.NewClientWithConfig(config)
}
```

**Comment by mwheeler-aicradle** [comment]
I second the question. Is Hz 4.x support on the roadmap? And more broadly, Is the Hz golang client being actively maintained? I'm starting a new project with an Hz backend, and need to choose a client language. My preference would be golang, but it's not clear to me if the golang client is actively maintained.

**Comment by justinrush** [comment]
I've just been using other in memory databases for now with an interface in front of them in case this ever looks like it will be maintained. I'm wondering if this PR is meant to fix it: https://github.com/hazelcast/hazelcast-go-client/pull/471

**Comment by yuce** [comment]
Hi @justinrush @mwheeler-aicradle, we have a new codebase for the Go client which supports only Hazelcast 4.x and up. Currently it's alpha and you can see the release notes and what we currently support at: https://github.com/hazelcast/hazelcast-go-client/releases/tag/v1.0.0-preview.1 Could you tell which Hazelcast features/distributed data structures do you use in your projects to help us with prioritizing the features to implement?

**Comment by yuce** [comment]
Closing this issue since we've recently released v1 which supports Hazelcast 4 and up: https://github.com/hazelcast/hazelcast-go-client/releases/tag/v1.0.0
